TEST: reemplazar ip del archivo env.js de forma dinamica

diff --git a/.github/workflows/DeployDestroy.yaml b/.github/workflows/DeployDestroy.yaml
--- a/.github/workflows/DeployDestroy.yaml
+++ b/.github/workflows/DeployDestroy.yaml
@@ -43,13 +43,36 @@ jobs:
         run: |
           echo "La IP pública de la instancia EC2 es: ${{ steps.get-ip.outputs.public_ip }}"
 
+      - name: Actualizar env.js con la nueva IP
+        run: |
+          cd client/config
+          if [ -f env.js ]; then
+            # Reemplazar solo lo que está entre // y :
+            sed -i -E "s|//[^:]+:|//${{ steps.get-ip.outputs.public_ip }}:|g" env.js
+            echo "Contenido actualizado de env.js:"
+            cat env.js
+          else
+            echo "Error: env.js no encontrado en client/config/"
+            exit 1
+          fi
+
+      - name: Commit y push de los cambios
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git add client/config/env.js
+          git commit -m "Update API endpoints with new EC2 IP: ${{ steps.get-ip.outputs.public_ip }}"
+          git push origin main
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Subir tfstate como artefacto
         uses: actions/upload-artifact@v4.4.3
         with:
           name: terraform-tfstate
           path: ./deploy/terraform.tfstate
 
-  destroy: 
+  destroy:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
